CREATE TABLE VOUCHER (
    VOUCHER_ID INTEGER NOT NULL,
VOUCHER_TEXT VARCHAR(1024),
COMPANY_NAME VARCHAR(256),
PRIMARY KEY (VOUCHER_ID)
)


CREATE TABLE CUSTOMER (
	CUSTOMER_ID INTEGER NOT NULL,
	EMAIL VARCHAR(256),
PRIMARY KEY (CUSTOMER_ID)
)


CREATE TABLE CUSTOMER_VOUCHER (
	ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER,
	VOUCHER_ID INTEGER,
PRIMARY KEY (ID)
)